# -------------------------------------------------------------------------------------
# Hugo Configuration
# See: https://gohugo.io/getting-started/configuration/
# -------------------------------------------------------------------------------------

baseURL = "https://example.org/"
buildDrafts = false
defaultContentLanguage = "en"
enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
hasCJKLanguage = true
languageCode = "en"
relativeURLs = false
summaryLength = 150
theme = [
  "FixIt",
  "shortcode-docs-bookmark",
]
title = "xdx blog"
# ignore some build errors
ignoreErrors = ["error-remote-getjson", "error-missing-instagram-accesstoken"]
